version: '3.8'

services:
  recycly-collector:
    build: .
    image: ghcr.io/zaidanig/recycly-collector:latest
    container_name: recycly_collector_app
    restart: unless-stopped
    ports:
      - "5001:5001"
    env_file:
      - .env
    volumes:
      - /home/zaidan/secrets/recycly-collector-firebase-key.json:/app/recycly-collector-firebase-adminsdk-fbsvc-9d44181f1b.json:ro
      - ./waste-collection:/app/waste-collection
    networks:
      - recycly-net

networks:
  recycly-net:
    driver: bridge